package mcp

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/wirvii/mneme/internal/managedblock"
	"github.com/wirvii/mneme/internal/service"
	"github.com/wirvii/mneme/internal/subagents"
)

// roleNamePattern is the safe-slug pattern every role name (whether one of
// the six built-in archetypes or a grill-invented custom role) must match:
// lowercase letters, digits, and hyphens, starting with a letter. This is
// deliberately restrictive — it is the primary defense against path
// traversal in subagent_write (a role like "../../../etc/cron.d/evil" must
// never reach filepath.Join) and against embedded-newline frontmatter
// injection in subagent_compose (Go's RE2 anchors "^"/"$" to the whole text
// by default, so a role containing "\n" can never match).
var roleNamePattern = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

// validateRoleName rejects role names that are empty or don't match
// roleNamePattern.
func validateRoleName(role string) error {
	if !roleNamePattern.MatchString(role) {
		return fmt.Errorf("invalid role name %q: must match %s", role, roleNamePattern.String())
	}
	return nil
}

// --- SUBAGENT HANDLERS (SPEC-057 / EPIC agnostic-agents SS-4) ---
//
// These six tools are thin MCP wiring over internal/subagents (SS-2, pure
// composition/validation) and internal/service.SubagentService (SS-3,
// persistence). No new business logic is introduced here beyond request/
// response shaping, archetype resolution, and the anti-prompt-injection
// wrap/escape applied to grill-provided layer-3 content in subagent_compose.

// subagentFingerprintRequest is the input to subagent_fingerprint.
type subagentFingerprintRequest struct {
	RepoRoot string `json:"repo_root"`
}

// subagentFingerprintResponse is the output of subagent_fingerprint.
type subagentFingerprintResponse struct {
	Root           string   `json:"root"`
	Apps           []string `json:"apps"`
	StackMarkers   []string `json:"stack_markers"`
	SeededMemories []string `json:"seeded_memories"`
	// ForeignAgents lists .claude/agents/*.md files (root-relative,
	// slash-separated) that were NOT generated by mneme — SPEC-090 D5, the
	// detection half of the fusion feature (BL-112). A file is foreign when
	// it lacks the agent-fixed managed block (subagents.IsForeignAgentFile —
	// a clean signal: every mneme-composed profile always carries it) OR
	// when its role has no corresponding entry in the current manifest.
	// Read-only; never offers to adopt or overwrite anything itself — that
	// is the grill's job (Phase 1/2 of Step 1, D6-D8).
	ForeignAgents []string `json:"foreign_agents"`
}

// handleSubagentFingerprint processes a subagent_fingerprint tool call: a
// deterministic, read-only filesystem probe (grill phase 0). It never writes
// anything and never calls an LLM.
func (h *handlers) handleSubagentFingerprint(ctx context.Context, raw json.RawMessage) (*ToolCallResult, *JSONRPCError) {
	var req subagentFingerprintRequest
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &req); err != nil {
			return nil, &JSONRPCError{
				Code:    CodeInvalidParams,
				Message: fmt.Sprintf("mcp: handle subagent_fingerprint: invalid arguments: %s", err),
			}
		}
	}

	root, rpcErr := resolveRepoRoot(req.RepoRoot)
	if rpcErr != nil {
		return nil, rpcErr
	}

	fp, err := subagents.NewStackFingerprinter().Fingerprint(root)
	if err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_fingerprint: %s", err),
		}
	}

	foreignAgents, err := h.detectForeignAgents(ctx, root)
	if err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_fingerprint: detect foreign agents: %s", err),
		}
	}

	return resultFromAny(subagentFingerprintResponse{
		Root:           fp.Root,
		Apps:           nonNilStrings(fp.Apps),
		StackMarkers:   nonNilStrings(fp.StackMarkers),
		SeededMemories: h.seededSubagentMemories(ctx),
		ForeignAgents:  nonNilStrings(foreignAgents),
	})
}

// detectForeignAgents lists every .claude/agents/*.md file under root
// (root-relative, slash-separated path) that is foreign to mneme (SPEC-090
// D5): either subagents.IsForeignAgentFile reports it lacks the agent-fixed
// managed block, or its role (the filename minus ".md") has no entry in the
// current project's manifest. Returns an empty, non-nil slice when the
// .claude/agents directory does not exist yet — not an error.
func (h *handlers) detectForeignAgents(ctx context.Context, root string) ([]string, error) {
	agentsDir := filepath.Join(root, ".claude", "agents")
	dirEntries, err := os.ReadDir(agentsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{}, nil
		}
		return nil, fmt.Errorf("read %s: %w", agentsDir, err)
	}

	manifest, err := h.subagentSvc.ReadManifest(ctx, "")
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}
	knownRoles := make(map[string]bool, len(manifest))
	for _, e := range manifest {
		knownRoles[string(e.Role)] = true
	}

	var foreign []string
	for _, entry := range dirEntries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		role := strings.TrimSuffix(entry.Name(), ".md")

		data, readErr := os.ReadFile(filepath.Join(agentsDir, entry.Name()))
		if readErr != nil {
			continue // unreadable file — never fabricate a foreign/not-foreign verdict for it
		}

		if subagents.IsForeignAgentFile(string(data)) || !knownRoles[role] {
			foreign = append(foreign, filepath.ToSlash(filepath.Join(".claude", "agents", entry.Name())))
		}
	}
	sort.Strings(foreign)
	return foreign, nil
}

// seededSubagentMemories reports which of the two typed-memory records the
// agnostic-agents EPIC persists (project-profile, manifest) already exist for
// the current project, so the grill's phase 0 can offer to reuse them instead
// of starting from scratch. Read-only; never creates anything.
func (h *handlers) seededSubagentMemories(ctx context.Context) []string {
	seeded := []string{}
	if profile, err := h.subagentSvc.ReadProfile(ctx, ""); err == nil && profile != nil {
		seeded = append(seeded, service.ProjectProfileTopicKey)
	}
	if manifest, err := h.subagentSvc.ReadManifest(ctx, ""); err == nil && manifest != nil {
		seeded = append(seeded, service.SubagentManifestTopicKey)
	}
	return seeded
}

// subagentProfileGetRequest is the input to subagent_profile_get.
type subagentProfileGetRequest struct {
	Project string `json:"project"`
}

// handleSubagentProfileGet processes a subagent_profile_get tool call.
// Returns an empty ProjectProfile (not an error) when none has been saved
// yet — mirrors SubagentService.ReadProfile's own not-found convention.
func (h *handlers) handleSubagentProfileGet(ctx context.Context, raw json.RawMessage) (*ToolCallResult, *JSONRPCError) {
	var req subagentProfileGetRequest
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &req); err != nil {
			return nil, &JSONRPCError{
				Code:    CodeInvalidParams,
				Message: fmt.Sprintf("mcp: handle subagent_profile_get: invalid arguments: %s", err),
			}
		}
	}

	profile, err := h.subagentSvc.ReadProfile(ctx, req.Project)
	if err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_profile_get: %s", err),
		}
	}
	if profile == nil {
		profile = &service.ProjectProfile{}
	}
	return resultFromAny(profile)
}

// subagentProfileSaveRequest is the input to subagent_profile_save.
type subagentProfileSaveRequest struct {
	Project     string                 `json:"project"`
	ProfileJSON service.ProjectProfile `json:"profile_json"`
}

// handleSubagentProfileSave processes a subagent_profile_save tool call:
// an idempotent upsert of the project-profile typed memory.
func (h *handlers) handleSubagentProfileSave(ctx context.Context, raw json.RawMessage) (*ToolCallResult, *JSONRPCError) {
	var req subagentProfileSaveRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_profile_save: invalid arguments: %s", err),
		}
	}

	resp, err := h.subagentSvc.SaveProfile(ctx, req.Project, req.ProfileJSON)
	if err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_profile_save: %s", err),
		}
	}
	return resultFromAny(resp)
}

// subagentComposeRequest is the input to subagent_compose.
type subagentComposeRequest struct {
	Role          string                 `json:"role"`
	Archetype     string                 `json:"archetype"`
	Model         string                 `json:"model"`
	Description   string                 `json:"description"`
	AreasLayer3MD string                 `json:"areas_layer3_md"`
	ProfileJSON   service.ProjectProfile `json:"profile_json"`
}

// subagentComposeResponse is the output of subagent_compose: a preview that
// is NEVER written to disk by this tool.
type subagentComposeResponse struct {
	Role       string   `json:"role"`
	Archetype  string   `json:"archetype"`
	ComposedMD string   `json:"composed_md"`
	Valid      bool     `json:"valid"`
	Errors     []string `json:"errors,omitempty"`
}

// handleSubagentCompose processes a subagent_compose tool call. It assembles
// layer-1 (agent-fixed, Go-authored) + the role's Go-authored permission
// envelope (selected via archetype, never generated content) with layer-2
// (profile_json, rendered as a project-context section) and layer-3
// (areas_layer3_md, wrapped and escaped as untrusted grill-provided data —
// see wrapUntrustedAreasContent), validates the result against archetype's
// PermissionTable entry, and returns the preview WITHOUT writing anything to
// disk. role may differ from archetype: custom roles map to one of the six
// built-in archetypes to inherit its allowlist (SPEC-052 §5.1), while the
// frontmatter `name:`/destination filename use the caller-supplied role.
func (h *handlers) handleSubagentCompose(_ context.Context, raw json.RawMessage) (*ToolCallResult, *JSONRPCError) {
	var req subagentComposeRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_compose: invalid arguments: %s", err),
		}
	}
	if req.Role == "" {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: "mcp: handle subagent_compose: role is required"}
	}
	if err := validateRoleName(req.Role); err != nil {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: fmt.Sprintf("mcp: handle subagent_compose: %s", err)}
	}
	if req.Archetype == "" {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: "mcp: handle subagent_compose: archetype is required"}
	}
	// I1: description is embedded verbatim as a frontmatter value
	// ("description: <value>") by frontmatter.SetFrontmatter, which does not
	// escape newlines. An embedded "\n" could inject a forged frontmatter
	// line (e.g. a fake "tools:"/"permissionMode:" key). Reject rather than
	// silently strip, so the caller notices and resubmits clean input.
	if strings.ContainsAny(req.Description, "\n\r") {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: "mcp: handle subagent_compose: description must not contain newlines",
		}
	}

	archetype := subagents.Role(req.Archetype)
	if _, ok := subagents.PermissionTable[archetype]; !ok {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_compose: unknown archetype %q (must be one of the built-in roles)", req.Archetype),
		}
	}

	// SPEC-090 D2/G1/G2: scan the RAW req.AreasLayer3MD (pre-wrap) for layer-1
	// leaks (lifecycle tools, capability keys) before it is ever wrapped or
	// composed. compose is the point of creation — rejecting here cuts the
	// leak at the source instead of letting it materialize into a file a
	// human has to notice later. Scanning the raw, unwrapped string (rather
	// than a later wrapped/escaped form) means this can never accidentally
	// widen into scanning layer-1 content — there is no layer-1 content in
	// this request field at all.
	if leaks := subagents.ScanLayer23Leaks(req.AreasLayer3MD); len(leaks) > 0 {
		return nil, &JSONRPCError{
			Code: CodeInvalidParams,
			Message: fmt.Sprintf(
				"mcp: handle subagent_compose: areas_layer3_md contains layer-1 content forbidden in layer 2/3 (lifecycle/capabilities): %s",
				formatLayer23Leaks(leaks)),
		}
	}

	modelVal := req.Model
	if modelVal == "" {
		modelVal = "sonnet"
	}
	description := req.Description
	if description == "" {
		description = fmt.Sprintf("Use this agent for %s work in this project.", req.Role)
	}

	composed, err := subagents.Compose("", subagents.ComposeInput{
		Role:        subagents.Role(req.Role),
		Archetype:   archetype,
		Description: description,
		Model:       modelVal,
		Body:        composeBody(req.ProfileJSON, req.AreasLayer3MD),
	})
	if err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_compose: %s", err),
		}
	}

	result := subagents.Validate(composed, archetype)

	return resultFromAny(subagentComposeResponse{
		Role:       req.Role,
		Archetype:  req.Archetype,
		ComposedMD: composed,
		Valid:      result.Valid,
		Errors:     result.Errors,
	})
}

// composeBody renders the layer-2 (profile) and layer-3 (areas) sections that
// seed a brand-new subagent profile's body. Only used when existing content
// is empty (subagent_compose always previews from scratch — regeneration
// against an on-disk file that preserves capa2-3 is a later, out-of-scope
// concern per SPEC-052 §2).
func composeBody(profile service.ProjectProfile, areasLayer3MD string) string {
	var parts []string
	if section := renderProjectContextSection(profile); section != "" {
		parts = append(parts, section)
	}
	if wrapped := wrapUntrustedAreasContent(areasLayer3MD); wrapped != "" {
		parts = append(parts, wrapped)
	}
	return strings.Join(parts, "\n\n")
}

// renderProjectContextSection renders profile's repo/org facts (layer 2) as
// a "## Contexto del proyecto" markdown section. Returns "" when profile
// carries no facts at all, so an empty profile_json never injects an empty
// heading.
func renderProjectContextSection(profile service.ProjectProfile) string {
	if profile.Org == "" && profile.Repo.Commits == "" && profile.Repo.Lang == "" &&
		profile.Repo.Layout == "" && len(profile.Repo.CrossRules) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("## Contexto del proyecto\n\n")
	if profile.Org != "" {
		fmt.Fprintf(&b, "- Organización: %s\n", profile.Org)
	}
	if profile.Repo.Commits != "" {
		fmt.Fprintf(&b, "- Convención de commits: %s\n", profile.Repo.Commits)
	}
	if profile.Repo.Lang != "" {
		fmt.Fprintf(&b, "- Stack: %s\n", profile.Repo.Lang)
	}
	if profile.Repo.Layout != "" {
		fmt.Fprintf(&b, "- Layout: %s\n", profile.Repo.Layout)
	}
	for _, rule := range profile.Repo.CrossRules {
		fmt.Fprintf(&b, "- Regla cross-cutting: %s\n", rule)
	}
	return strings.TrimRight(b.String(), "\n")
}

// formatLayer23Leaks renders leaks as a comma-separated "token" (line N)
// list for a JSONRPCError message — SPEC-090 D2 requires the guard to name
// token+line so the grill can re-synthesize precisely instead of guessing
// what to strip.
func formatLayer23Leaks(leaks []subagents.Layer23Leak) string {
	parts := make([]string, 0, len(leaks))
	for _, leak := range leaks {
		parts = append(parts, fmt.Sprintf("%q (line %d)", leak.Token, leak.Line))
	}
	return strings.Join(parts, ", ")
}

// wrapUntrustedAreasContent wraps areasLayer3MD in a fixed envelope marking
// it explicitly as untrusted, grill-provided DATA — never a new instruction
// that could override the agent-fixed layer-1 block, the role's permission
// envelope, or the cross-cutting protocol above it in the composed profile.
// Any literal occurrence of mneme's managed-block marker syntax
// ("<!-- mneme:...") or of this function's own wrap delimiters is escaped
// first, so injected content can never forge a fake managed-block boundary
// or smuggle text past its own wrap. Returns "" for blank input, so an empty
// areas_layer3_md never injects an empty wrapped block.
//
// subagents.GrillContentWrapStart/End (SPEC-090 D1) is the single source of
// truth for these delimiters — subagents.ExtractGrillRegion reads exactly
// the same two constants, so the wrap step here and the guard/doctor's
// extraction step can never independently drift out of sync.
func wrapUntrustedAreasContent(areasLayer3MD string) string {
	trimmed := strings.TrimSpace(areasLayer3MD)
	if trimmed == "" {
		return ""
	}
	escaped := escapeManagedBlockMarkers(trimmed)
	return subagents.GrillContentWrapStart + "\n\n" + escaped + "\n\n" + subagents.GrillContentWrapEnd
}

// escapeManagedBlockMarkers neutralizes literal occurrences of mneme's
// managed-block marker prefix and of the wrap delimiters themselves inside s,
// by prefixing them with a backslash so they render as inert text.
func escapeManagedBlockMarkers(s string) string {
	replacer := strings.NewReplacer(
		"<!-- mneme:", "\\<!-- mneme:",
		subagents.GrillContentWrapStart, "\\"+subagents.GrillContentWrapStart,
		subagents.GrillContentWrapEnd, "\\"+subagents.GrillContentWrapEnd,
	)
	return replacer.Replace(s)
}

// subagentWriteRequest is the input to subagent_write.
type subagentWriteRequest struct {
	Role            string   `json:"role"`
	Archetype       string   `json:"archetype"`
	ComposedMD      string   `json:"composed_md"`
	EnforcementHook bool     `json:"enforcement_hook"`
	Project         string   `json:"project"`
	RepoRoot        string   `json:"repo_root"`
	Engine          string   `json:"engine"`
	Areas           []string `json:"areas"`
	// AreasComplete certifies Areas as an exhaustive list of every path this
	// role may write to (SPEC-086 D4/D5/D11). Must never be inferred or
	// backfilled automatically — only set true in response to the
	// mneme-init grill's explicit completeness question.
	AreasComplete bool `json:"areas_complete"`
}

// subagentWriteResponse is the output of subagent_write.
type subagentWriteResponse struct {
	Path      string                  `json:"path"`
	Checksum  string                  `json:"checksum"`
	Version   int                     `json:"version"`
	Artifacts []service.AgentArtifact `json:"artifacts,omitempty"`
	// BackupPath is the path subagent_write backed up the pre-existing
	// developer-authored file to (SPEC-090 D9), or "" when no backup was
	// made (the destination did not exist, or was already ours).
	BackupPath string `json:"backup_path,omitempty"`
}

// handleSubagentWrite processes a subagent_write tool call: it writes
// composed_md to .claude/agents/<role>.md (via SubagentService.WriteAgentProfiles,
// which is itself atomic-with-rollback for the write step) and then updates
// the manifest (via SubagentService.SaveManifest). If the manifest update
// fails AFTER the file write already succeeded, the file write is manually
// rolled back to its exact pre-call state so the two steps together remain
// atomic from the caller's perspective.
//
// Two hard security invariants are enforced BEFORE anything is written:
//
//   - C1 (path traversal): role must match roleNamePattern (rejects "..",
//     "/", and any other character that could escape the destination
//     .claude/agents/ directory), and the final resolved path is additionally
//     confirmed to still live inside that directory via filepath.Rel — belt
//     and suspenders against any future change to how the path is built.
//   - C2 (permission-envelope tampering): composed_md is validated against
//     archetype's Go-authored PermissionTable entry via subagents.Validate,
//     the SAME check subagent_compose itself runs. A hand-crafted composed_md
//     whose "tools:"/"permissionMode:" exceed the archetype's allowlist (e.g.
//     granting Edit/Write/Bash + bypassPermissions to a role that should map
//     to the read-only "qa-tester"/"architect" archetype) is rejected —
//     subagent_write must never trust that a caller-supplied composed_md
//     actually came from subagent_compose.
func (h *handlers) handleSubagentWrite(ctx context.Context, raw json.RawMessage) (*ToolCallResult, *JSONRPCError) {
	var req subagentWriteRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_write: invalid arguments: %s", err),
		}
	}
	if req.Role == "" {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: "mcp: handle subagent_write: role is required"}
	}
	if err := validateRoleName(req.Role); err != nil {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: fmt.Sprintf("mcp: handle subagent_write: %s", err)}
	}
	if req.Archetype == "" {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: "mcp: handle subagent_write: archetype is required"}
	}
	archetype := subagents.Role(req.Archetype)
	if _, ok := subagents.PermissionTable[archetype]; !ok {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_write: unknown archetype %q (must be one of the built-in roles)", req.Archetype),
		}
	}
	if strings.TrimSpace(req.ComposedMD) == "" {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: "mcp: handle subagent_write: composed_md is required"}
	}
	if validation := subagents.Validate(req.ComposedMD, archetype); !validation.Valid {
		return nil, &JSONRPCError{
			Code: CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_write: composed_md failed validation against archetype %q: %s",
				req.Archetype, strings.Join(validation.Errors, "; ")),
		}
	}
	// SPEC-090 D2/G2 (the critical property): write receives composed_md, not
	// areas_layer3_md — a hand-edited composed_md could smuggle a leak compose
	// never saw. Extract ONLY the grill region (subagents.ExtractGrillRegion)
	// and scan THAT — never the whole composed_md. The layer-1 agent-fixed
	// block legitimately says "NUNCA llames spec_advance"; scanning the whole
	// document would reject that legitimate prohibition forever (the
	// guardián-ciego-opuesto AC4 exists to prevent). When no grill region is
	// found at all (ok=false — e.g. a hand-authored profile with no wrapped
	// layer-3 content), there is nothing to scan and nothing to reject here.
	if region, ok := subagents.ExtractGrillRegion(req.ComposedMD); ok {
		if leaks := subagents.ScanLayer23Leaks(region); len(leaks) > 0 {
			return nil, &JSONRPCError{
				Code: CodeInvalidParams,
				Message: fmt.Sprintf(
					"mcp: handle subagent_write: composed_md's grill region contains layer-1 content forbidden in layer 2/3 (lifecycle/capabilities): %s",
					formatLayer23Leaks(leaks)),
			}
		}
	}

	root, rpcErr := resolveRepoRoot(req.RepoRoot)
	if rpcErr != nil {
		return nil, rpcErr
	}
	agentsDir := filepath.Join(root, ".claude", "agents")
	path := filepath.Join(agentsDir, req.Role+".md")
	if rel, err := filepath.Rel(agentsDir, path); err != nil || rel != req.Role+".md" {
		return nil, &JSONRPCError{
			Code:    CodeInvalidParams,
			Message: fmt.Sprintf("mcp: handle subagent_write: role %q resolves outside the agents directory", req.Role),
		}
	}
	contract, err := subagents.ContractFromClaude(req.ComposedMD, archetype)
	if err != nil {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: fmt.Sprintf("mcp: handle subagent_write: derive canonical contract: %s", err)}
	}
	codexContent, err := subagents.RenderCodex(contract)
	if err != nil {
		return nil, &JSONRPCError{Code: CodeInvalidParams, Message: fmt.Sprintf("mcp: handle subagent_write: render Codex profile: %s", err)}
	}
	codexPath := filepath.Join(root, ".codex", "agents", req.Role+".toml")

	originalBytes, readErr := os.ReadFile(path)
	existed := readErr == nil
	if readErr != nil && !os.IsNotExist(readErr) {
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_write: read existing %s: %s", path, readErr),
		}
	}

	// SPEC-090 D9: back up the pre-existing file BEFORE overwriting it, but
	// ONLY when it existed AND was not ours to begin with (no agent-fixed
	// block — i.e. it is a developer's own hand-authored agent that
	// subagent_write is about to clobber). Overwriting a file mneme itself
	// generated is idempotent regeneration already traced by git/the
	// manifest — backing it up every time would be pure churn, not a safety
	// net. The backup lives in the repo (git-visible), never in scratchpad.
	var backupPath string
	if existed && subagents.IsForeignAgentFile(string(originalBytes)) {
		backupPath = path + ".bak-" + time.Now().UTC().Format("20060102T150405Z")
		if err := os.WriteFile(backupPath, originalBytes, 0o644); err != nil {
			return nil, &JSONRPCError{
				Code:    CodeInternalError,
				Message: fmt.Sprintf("mcp: handle subagent_write: back up existing %s: %s", path, err),
			}
		}
	}

	codexOriginal, codexReadErr := os.ReadFile(codexPath)
	codexExisted := codexReadErr == nil
	if codexReadErr != nil && !os.IsNotExist(codexReadErr) {
		return nil, &JSONRPCError{Code: CodeInternalError, Message: fmt.Sprintf("mcp: handle subagent_write: read existing %s: %s", codexPath, codexReadErr)}
	}

	if _, err := h.subagentSvc.WriteAgentProfiles([]service.WriteAgentFile{
		{Role: subagents.Role(req.Role), Path: path, Content: req.ComposedMD},
		{Role: subagents.Role(req.Role), Path: codexPath, Content: codexContent},
	}); err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_write: %s", err),
		}
	}

	_, version, _ := managedblock.ReadText(req.ComposedMD, "agent-fixed")
	checksum := checksumOf(req.ComposedMD)
	codexChecksum := checksumOf(codexContent)
	engine := req.Engine
	if engine == "" {
		engine = "passthrough"
	}

	entries, err := h.subagentSvc.ReadManifest(ctx, req.Project)
	if err != nil {
		rollbackAgentFile(path, existed, originalBytes)
		rollbackAgentFile(codexPath, codexExisted, codexOriginal)
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_write: read manifest: %s (file write rolled back)", err),
		}
	}

	entries = upsertManifestEntry(entries, service.ManifestEntry{
		Role:     subagents.Role(req.Role),
		Path:     manifestRelativePath(req.Role),
		Version:  version,
		Checksum: checksum,
		Artifacts: []service.AgentArtifact{
			{Runtime: subagents.RuntimeClaudeCode, Path: manifestRelativePath(req.Role), Checksum: checksum},
			{Runtime: subagents.RuntimeCodex, Path: filepath.ToSlash(filepath.Join(".codex", "agents", req.Role+".toml")), Checksum: codexChecksum},
		},
		Areas:           req.Areas,
		Archetype:       archetype,
		AreasComplete:   req.AreasComplete,
		Engine:          engine,
		GeneratedAt:     time.Now().UTC(),
		EnforcementHook: req.EnforcementHook,
	})

	if _, err := h.subagentSvc.SaveManifest(ctx, req.Project, entries); err != nil {
		rollbackAgentFile(path, existed, originalBytes)
		rollbackAgentFile(codexPath, codexExisted, codexOriginal)
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_write: save manifest: %s (file write rolled back)", err),
		}
	}

	return resultFromAny(subagentWriteResponse{
		Path:     path,
		Checksum: checksum,
		Version:  version,
		Artifacts: []service.AgentArtifact{
			{Runtime: subagents.RuntimeClaudeCode, Path: path, Checksum: checksum},
			{Runtime: subagents.RuntimeCodex, Path: codexPath, Checksum: codexChecksum},
		},
		BackupPath: backupPath,
	})
}

// rollbackAgentFile restores path to its exact pre-write state: rewritten
// with original when it existed before the call, removed otherwise. Errors
// are deliberately swallowed (best-effort rollback on an already-failing
// path — matches SubagentService.WriteAgentProfiles' own rollback closure).
func rollbackAgentFile(path string, existed bool, original []byte) {
	if existed {
		_ = os.WriteFile(path, original, 0o644)
	} else {
		_ = os.Remove(path)
	}
}

// checksumOf returns the lowercase hex-encoded sha256 digest of content.
func checksumOf(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

// manifestRelativePath returns the root-relative, slash-separated form of a
// freshly written profile's destination (".claude/agents/<role>.md") —
// SPEC-089 Part 2 (D3): a brand-new manifest entry's Path is persisted
// relative-to-root from the moment it is written, never absolute. The actual
// filesystem write still uses the caller's absolute `path` (root-confined,
// validated above); only the value PERSISTED in the manifest changes. Mirrors
// internal/cli/subagents.go's manifestRelativePath.
func manifestRelativePath(role string) string {
	return filepath.ToSlash(filepath.Join(".claude", "agents", role+".md"))
}

// upsertManifestEntry replaces the entry matching entry.Role in entries, or
// appends entry when no matching role is found.
func upsertManifestEntry(entries []service.ManifestEntry, entry service.ManifestEntry) []service.ManifestEntry {
	for i, e := range entries {
		if e.Role == entry.Role {
			entries[i] = entry
			return entries
		}
	}
	return append(entries, entry)
}

// subagentManifestListRequest is the input to subagent_manifest_list.
type subagentManifestListRequest struct {
	Project string `json:"project"`
}

// subagentManifestListEntry embeds service.ManifestEntry (so
// encoding/json flattens every persisted field at the top level, exactly
// matching the pre-SPEC-086 response shape) and adds Findings — the SPEC-086
// D11/D12 doctor diagnostics for this entry. This keeps
// subagent_manifest_list backward compatible: a caller that still
// unmarshals into []service.ManifestEntry (every AC1-era test in this repo
// does exactly that) silently ignores the extra "findings" key, since Go's
// encoding/json drops JSON fields absent from the destination struct. A new
// caller — critically, the mneme-init grill, which runs over MCP and is the
// one place D11's diagnostics are actually meant to feed back into a
// repair workflow (CLI-only doctor findings are invisible to it) — can read
// Findings directly.
type subagentManifestListEntry struct {
	service.ManifestEntry
	Findings []mcpDoctorFinding `json:"findings,omitempty"`
}

// handleSubagentManifestList processes a subagent_manifest_list tool call.
func (h *handlers) handleSubagentManifestList(ctx context.Context, raw json.RawMessage) (*ToolCallResult, *JSONRPCError) {
	var req subagentManifestListRequest
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &req); err != nil {
			return nil, &JSONRPCError{
				Code:    CodeInvalidParams,
				Message: fmt.Sprintf("mcp: handle subagent_manifest_list: invalid arguments: %s", err),
			}
		}
	}

	entries, err := h.subagentSvc.ReadManifest(ctx, req.Project)
	if err != nil {
		return nil, &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: handle subagent_manifest_list: %s", err),
		}
	}

	// SPEC-089 Part 1: root confines every entry's Path for the foreign_path
	// check. subagent_manifest_list takes no repo_root argument (deliberately
	// no new request field — see the design's "no new public API"), so root
	// is always the process cwd, mirroring cli's doctor command.
	root, rpcErr := resolveRepoRoot("")
	if rpcErr != nil {
		return nil, rpcErr
	}

	out := make([]subagentManifestListEntry, 0, len(entries))
	for _, e := range entries {
		out = append(out, subagentManifestListEntry{
			ManifestEntry: e,
			Findings:      diagnoseManifestEntryMCP(e, root, mcpRealFileExists, mcpRealChecksum, mcpRealReadContent),
		})
	}
	return resultFromAny(out)
}

// resolveRepoRoot returns explicit when non-empty, otherwise the current
// working directory. Wrapped as a JSONRPCError so callers can return it
// directly.
func resolveRepoRoot(explicit string) (string, *JSONRPCError) {
	if explicit != "" {
		return explicit, nil
	}
	dir, err := os.Getwd()
	if err != nil {
		return "", &JSONRPCError{
			Code:    CodeInternalError,
			Message: fmt.Sprintf("mcp: subagents: resolve repo root: %s", err),
		}
	}
	return dir, nil
}

// nonNilStrings returns s unchanged when non-nil, or an empty (non-nil)
// slice otherwise — avoids serializing JSON null for array fields.
func nonNilStrings(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

// --- SPEC-086 D11/D12: doctor diagnostics surfaced over MCP -----------------
//
// This mirrors internal/cli/subagents_doctor.go's diagnoseManifestEntry
// (kind constants, struct shape, and check ordering) rather than importing
// it: mneme's three frontends are peers that call into service/leaf layers
// directly and do not import each other (see this file's own composeBody/
// checksumOf/upsertManifestEntry, all already duplicated from
// internal/cli/subagents.go for the same reason). D12 requires this
// diagnostic to be reachable over MCP specifically because the mneme-init
// grill — the one thing D11 expects to actually repair a manifest — runs
// over MCP, not the CLI; a CLI-only doctor is invisible to it.
//
// The one thing intentionally NOT duplicated is cli's areaMatches/cleanArea
// (SPEC-084 D1/D2, unexported in internal/cli/hook.go): the bare-directory
// finding here uses a simpler, purely informational isGlobLike check
// instead of full glob-normalisation semantics — sufficient for advisory
// output, since this finding is never actionable (mcpDoctorFindingKind's
// bareDirOK case) and never feeds an enforcement decision.

// mcpDoctorFindingKind classifies a single diagnostic finding (mirrors
// cli's doctorFindingKind).
type mcpDoctorFindingKind string

const (
	mcpDoctorKindUnknownRole      mcpDoctorFindingKind = "unknown_role"
	mcpDoctorKindDegenerateAreas  mcpDoctorFindingKind = "degenerate_areas"
	mcpDoctorKindArchetypeMissing mcpDoctorFindingKind = "archetype_missing"
	mcpDoctorKindNotVerified      mcpDoctorFindingKind = "not_verified"
	mcpDoctorKindOrphanPath       mcpDoctorFindingKind = "orphan_path"
	mcpDoctorKindDrift            mcpDoctorFindingKind = "drift"
	mcpDoctorKindBareDirOK        mcpDoctorFindingKind = "bare_dir_ok"
	// mcpDoctorKindStaleAgentFixed mirrors cli's doctorKindStaleAgentFixed
	// (SPEC-087 D7/R7): fires when a manifest entry's persisted Version has
	// fallen behind subagents.AgentFixedVersion. NOT auto-fixed by --fix
	// (SPEC-086 AC16 stays green) — the mneme-init grill is the one place
	// D11 expects a repair workflow to actually act on this, per this
	// file's own package doc comment.
	mcpDoctorKindStaleAgentFixed mcpDoctorFindingKind = "stale_agent_fixed"

	// mcpDoctorKindForeignPath mirrors cli's doctorKindForeignPath
	// (SPEC-089 Part 1): a manifest entry's Path fails
	// subagents.ResolveManifestPath against the current repo root — an
	// absolute path from a different repo checkout, or one authored on a
	// different OS family. Checked before orphan_path/drift, since a foreign
	// path is never confined and those two checks would be meaningless for
	// it. Actionable, but never removes the entry.
	mcpDoctorKindForeignPath mcpDoctorFindingKind = "foreign_path"

	// mcpDoctorKindLifecycleInLayer23 mirrors cli's
	// doctorKindLifecycleInLayer23 (SPEC-090 D3): fires when
	// subagents.DetectLayer23Leaks finds an SDD lifecycle token or
	// capability key already materialized inside a manifest entry's grill
	// region on disk. Report-only — the mneme-init grill, which runs over
	// MCP, is the one place expected to actually re-synthesize the leaked
	// content out.
	mcpDoctorKindLifecycleInLayer23 mcpDoctorFindingKind = "lifecycle_in_layer23"
)

// mcpDoctorFinding is one diagnostic observation about a single manifest
// entry, returned inline on subagent_manifest_list (mirrors cli's
// doctorFinding, minus the redundant Role field — the caller already knows
// which entry a given Findings slice belongs to).
type mcpDoctorFinding struct {
	Kind   mcpDoctorFindingKind `json:"kind"`
	Detail string               `json:"detail"`
}

// diagnoseManifestEntryMCP runs the same checks as cli's
// diagnoseManifestEntry against a single manifest entry. fileExists/
// actualChecksum/readContent are injected so the function is testable
// without touching the real filesystem. root confines e.Path (SPEC-089
// Part 1) via the same subagents.ResolveManifestPath call regen and cli's
// doctor use, so this mirror can never disagree with them about what counts
// as foreign. readContent (SPEC-090 D3) feeds subagents.DetectLayer23Leaks
// for the lifecycle_in_layer23 finding — injected in parallel to
// actualChecksum, for the same reason.
func diagnoseManifestEntryMCP(e service.ManifestEntry, root string, fileExists func(string) bool, actualChecksum func(string) (string, bool), readContent func(string) (string, bool)) []mcpDoctorFinding {
	var findings []mcpDoctorFinding
	archetype := e.EffectiveArchetype()

	if _, known := subagents.PermissionTable[archetype]; !known {
		findings = append(findings, mcpDoctorFinding{
			Kind:   mcpDoctorKindUnknownRole,
			Detail: fmt.Sprintf("archetype/role %q no está en PermissionTable — no es implementador para el hook, su área está desprotegida", archetype),
		})
	} else if subagents.IsImplementer(archetype) && len(e.Areas) == 0 {
		findings = append(findings, mcpDoctorFinding{
			Kind:   mcpDoctorKindDegenerateAreas,
			Detail: "rol implementador sin áreas declaradas (degenerado)",
		})
	}

	if e.Archetype == "" {
		findings = append(findings, mcpDoctorFinding{
			Kind:   mcpDoctorKindArchetypeMissing,
			Detail: "archetype ausente — backfill mecánico disponible (mneme subagents doctor --fix)",
		})
	}
	if !e.AreasComplete {
		findings = append(findings, mcpDoctorFinding{
			Kind:   mcpDoctorKindNotVerified,
			Detail: "areas_complete ausente o false — no verificado (re-grillar para certificar)",
		})
	}
	if e.Version < subagents.AgentFixedVersion {
		findings = append(findings, mcpDoctorFinding{
			Kind:   mcpDoctorKindStaleAgentFixed,
			Detail: fmt.Sprintf("agent-fixed block en v%d, la versión actual es v%d — regenerar con `mneme subagents regen --role %s`", e.Version, subagents.AgentFixedVersion, e.Role),
		})
	}

	if e.Path != "" {
		if _, _, ok := subagents.ResolveManifestPath(e.Path, root); !ok {
			findings = append(findings, mcpDoctorFinding{
				Kind:   mcpDoctorKindForeignPath,
				Detail: fmt.Sprintf("path %q está fuera de la raíz del proyecto o es foráneo-de-otro-SO — `regen` la omite, nunca la toca (SPEC-089)", e.Path),
			})
		} else if !fileExists(e.Path) {
			findings = append(findings, mcpDoctorFinding{
				Kind:   mcpDoctorKindOrphanPath,
				Detail: fmt.Sprintf("path %q no existe en disco (huérfano)", e.Path),
			})
		} else {
			if e.Checksum != "" {
				if actual, ok := actualChecksum(e.Path); ok && actual != e.Checksum {
					findings = append(findings, mcpDoctorFinding{
						Kind:   mcpDoctorKindDrift,
						Detail: "checksum en disco no coincide con el manifest (drift)",
					})
				}
			}
			for _, leak := range subagents.DetectLayer23Leaks(e.Path, readContent) {
				findings = append(findings, mcpDoctorFinding{
					Kind:   mcpDoctorKindLifecycleInLayer23,
					Detail: fmt.Sprintf("fuga de capa 1 (%s) en la región de capa 2/3: %q, línea %d — re-grillar el rol para limpiarlo", leak.Kind, leak.Token, leak.Line),
				})
			}
		}
	}

	for _, area := range e.Areas {
		trimmed := strings.TrimSpace(area)
		if trimmed == "" || trimmed == "." || trimmed == "./" {
			continue
		}
		if !mcpIsGlobLike(trimmed) {
			findings = append(findings, mcpDoctorFinding{
				Kind:   mcpDoctorKindBareDirOK,
				Detail: fmt.Sprintf("area %q es un directorio desnudo — areaMatches ya lo resuelve, sano", area),
			})
		}
	}

	return findings
}

// mcpIsGlobLike reports whether area already contains glob metacharacters
// (mirrors cli's isGlobLike).
func mcpIsGlobLike(area string) bool {
	for _, r := range area {
		switch r {
		case '*', '?', '[':
			return true
		}
	}
	return false
}

// mcpRealFileExists/mcpRealChecksum/mcpRealReadContent are the production
// fileExists/actualChecksum/readContent implementations diagnoseManifestEntryMCP
// is wired with outside tests (mirrors cli's
// realFileExists/realChecksum/realReadContent).
func mcpRealFileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func mcpRealChecksum(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), true
}

// mcpRealReadContent is the production readContent implementation
// diagnoseManifestEntryMCP is wired with outside tests (SPEC-090 D3, mirrors
// cli's realReadContent).
func mcpRealReadContent(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return string(data), true
}
