package install

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"

	"github.com/wirvii/mneme/internal/managedblock"
)

// commandBlockMarker identifies the managed block that fences a slash
// command asset's instruction body (SPEC-141 §4-bis D16). Unlike
// managedBlockMarker (used for CLAUDE.md/AGENTS.md, where the block sits
// inside a much larger file the person also owns), a command asset's
// frontmatter (the "---" YAML header) is the only part of the file left
// OUTSIDE the block — the body is the block, start to end. Using
// internal/managedblock here (rather than a bespoke check) means a command
// file already tolerates CRLF and recognises any marker version, for the
// same reasons documented on managedblock.StartMarkerPrefix.
const commandBlockMarker = "command"

// legacyCommandDigests maps a command name (a slash-command asset's
// basename without extension, e.g. "mneme-init") to the SHA-256 hex digests
// of every content this repository's own git history shows mneme ever
// wrote to a person's ~/.claude/commands/ directory BEFORE the
// commandBlockMarker existed (SPEC-141 §4-bis D17). Without this table, the
// FIRST install after this marker ships would misclassify every one of
// those pre-marker files as foreign and refuse to update them — including
// a "grill-me.md" installed by mneme itself, months ago, on a real
// developer's machine (the case BL-228/AC12 exists to fix).
//
// CLOSED BY CONSTRUCTION: once commandBlockMarker exists in an asset, every
// file mneme writes from then on carries it and is recognised by the marker
// alone (isKnownLegacyDigest is only ever consulted for a destination file
// that predates this table). This table therefore never grows again after
// the mneme version that introduces it ships.
//
// Generated by walking this repository's own git history — the exact
// commands used, repeated for every command asset added to this table:
//
//	git log --follow --name-status --format='COMMIT %H' -- internal/install/assets/commands/<name>.md
//	git show <sha>:internal/install/assets/commands/<name>.md | sha256sum
//
// See changes.md for the full transcript. Its declared limit: a historical
// variant this walk did not find stays classified as foreign — the visible,
// safe-side symptom is a "kept yours" notice, never a silent overwrite.
//
// This table only carries "mneme-init" for now (C1, SPEC-141): it is the
// only command asset ClaudeCode's Commands closure installs at this point
// in the change. grill-me/hunt-bug/bug-to-issue join once C3 makes them
// installable too — adding their entries any earlier would be dead data
// no code path could ever exercise.
var legacyCommandDigests = map[string][]string{
	"mneme-init": {
		// The obsolete 5-phase project-init markdown (pre-SPEC-067 restore),
		// commit bf27e42f0b70d1c5450deac04b1f083c458e02a9.
		"f39834833c75af91d1a51290f299d503ee8c9c13848b7f457ef9926c1a55620a",
		// The thin wrapper exactly as it read before this spec (SPEC-141)
		// added commandBlockMarker, commit
		// 621bb95caa839b37d9a87b88f366d0052381411a — this repository's own
		// HEAD immediately before this change, captured verbatim in
		// testdata/legacy-commands/mneme-init.md (AC12).
		"915b28d189777df00bbee5680e2c727f9991a0a3a559f7067acf569f5fa33fc2",
	},
}

// CommandOwnershipNotice is the message internal/cli/install.go prints when
// the "Slash commands" install step reports one or more command files it
// left untouched (SPEC-141 §4-bis D18): those files were not written by
// mneme, so mneme leaves them exactly as they are instead of overwriting
// them. Exported so the CLI never repeats this text as a second, separately
// maintained literal — the same reason refinementAdvisoryText is a single
// constant (SPEC-103).
const CommandOwnershipNotice = `mneme found existing slash command file(s) it did not create, and left them unchanged.
To replace one of them with mneme's own version, delete the file and run "mneme install claude-code" again,
or run "mneme install claude-code --force" to replace all of them at once (mneme keeps a ".bak" copy of
each original file next to it, so nothing is lost).`

// CommandKeptYoursLabel is the label WriteCommands' caller (the "Slash
// commands" install step) prefixes its detail string with when one or more
// command files were left untouched. Exported so internal/cli/install.go can
// detect that case from the detail string and print CommandOwnershipNotice
// without re-deriving or duplicating the literal text.
const CommandKeptYoursLabel = "kept yours (not replaced)"

// commandFileDigest returns the lowercase hex SHA-256 digest of data — the
// same encoding `sha256sum` prints, so legacyCommandDigests entries can be
// derived and cross-checked with the exact shell command in that table's
// own godoc.
func commandFileDigest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// isKnownLegacyDigest reports whether digest matches one of the historical
// versions recorded for name in legacyCommandDigests.
func isKnownLegacyDigest(name, digest string) bool {
	for _, d := range legacyCommandDigests[name] {
		if d == digest {
			return true
		}
	}
	return false
}

// commandOwnership classifies a destination slash-command file per SPEC-141
// §4-bis D15.
type commandOwnership int

const (
	// commandAbsent means the destination file does not exist yet.
	commandAbsent commandOwnership = iota

	// commandOurs means the destination file is recognised as mneme's own —
	// either it carries commandBlockMarker, or its raw bytes match a known
	// pre-marker digest in legacyCommandDigests.
	commandOurs

	// commandForeign means the destination file exists but is neither of the
	// above: mneme did not write it, and installing must not overwrite it
	// without --force.
	commandForeign
)

// classifyCommandFile reads the destination file at path (whose command
// name is name, e.g. "hunt-bug") and classifies its ownership per SPEC-141
// §4-bis D15/D16/D17. It returns the file's existing raw content (nil when
// commandAbsent) and, when the file is recognised as ours, whether that
// recognition came from the managed-block marker (already-current
// generation) rather than a legacy digest (pre-marker generation adopted
// for the first time) — the caller uses this only to decide between
// reporting "updated" and "adopted" (SPEC-141 D18), never to change what
// gets written: both cases write the exact same new content.
func classifyCommandFile(path, name string) (ownership commandOwnership, existing []byte, viaMarker bool, err error) {
	data, readErr := os.ReadFile(path)
	if readErr != nil {
		if os.IsNotExist(readErr) {
			return commandAbsent, nil, false, nil
		}
		return commandForeign, nil, false, fmt.Errorf("install: classify command file %s: %w", path, readErr)
	}

	if _, _, present := managedblock.ReadText(string(data), commandBlockMarker); present {
		return commandOurs, data, true, nil
	}
	if isKnownLegacyDigest(name, commandFileDigest(data)) {
		return commandOurs, data, false, nil
	}
	return commandForeign, data, false, nil
}
