package subagents

import "github.com/wirvii/mneme/internal/managedblock"

// IsForeignAgentFile reports whether content — the raw text of a
// .claude/agents/<role>.md file — was NOT generated by mneme: it lacks the
// "agent-fixed" managed block every mneme-composed profile always carries
// (see composer.go's agentFixedMarker/Compose). This is a clean, mechanical
// signal (SPEC-090 D5) — a profile mneme wrote always has the block; one a
// developer authored by hand, or brought from another tool, never does.
//
// It intentionally does NOT inspect the manifest (whether a role has a
// corresponding entry) — that cross-check belongs to the caller
// (subagent_fingerprint's foreign_agents detection), which has access to
// SubagentService.ReadManifest; this leaf function only ever looks at the
// bytes it is given.
func IsForeignAgentFile(content string) bool {
	_, _, present := managedblock.ReadText(content, agentFixedMarker)
	return !present
}
