package subagents

import "strings"

// Role identifies one of mneme's bundled subagent roles. Role values are
// Go-authored constants, never generated by an LLM — they are the anchor
// PermissionTable keys on.
type Role string

// The six roles mneme ships today (internal/install/assets/agents/*.md).
// StackFingerprinter/grill-driven role selection (SS-3+) may introduce new
// roles in the future, but the permission envelope for these six is fixed
// here and must never be widened by generated content.
const (
	RoleArchitect     Role = "architect"
	RoleBackend       Role = "backend"
	RoleFrontend      Role = "frontend"
	RoleQATester      Role = "qa-tester"
	RoleBugHunter     Role = "bug-hunter"
	RoleDiagnostician Role = "diagnostician"
)

// Permission describes the exact `tools:` allowlist and (optional)
// `permissionMode:` value a role's frontmatter must carry. This is the
// capability layer described in SPEC-034/SPEC-052 D3: an LLM never generates
// these values, so a subagent can never grant itself more capability than
// its role allows.
type Permission struct {
	// Tools lists the frontmatter tools allowlist in the exact order it must
	// appear on the `tools:` line.
	Tools []string

	// PermissionMode is the frontmatter `permissionMode:` value, or "" when
	// the role must NOT carry that key at all (read-only roles never bypass
	// Claude Code's permission prompts).
	PermissionMode string
}

// ToolsString renders Tools as the comma-and-space-joined string used
// verbatim on an agent's frontmatter `tools:` line, e.g.
// "Read, Grep, Glob, NotebookRead, BashOutput, mcp__mneme__*".
func (p Permission) ToolsString() string {
	return strings.Join(p.Tools, ", ")
}

// readOnlyTools is the allowlist shared by roles that only ever read code:
// no Edit/Write/MultiEdit/NotebookEdit, no Bash.
var readOnlyTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "BashOutput", "mcp__mneme__*",
}

// implementerTools is the allowlist shared by roles that implement code:
// full edit toolset plus Bash.
var implementerTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "NotebookEdit", "BashOutput",
	"Edit", "Write", "MultiEdit", "Bash", "mcp__mneme__*",
}

// diagnosticianTools is readOnlyTools plus Bash (for reading logs/infra) but
// without any edit tool — the diagnostician reads and triages, never mutates.
var diagnosticianTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "BashOutput", "Bash", "mcp__mneme__*",
}

// bypassPermissions is the frontmatter permissionMode value implementer
// roles carry so autonomous runs are not interrupted by per-tool prompts.
// The real capability barrier is the tools: allowlist above, not this mode.
const bypassPermissions = "bypassPermissions"

// PermissionTable is the Go-authored, constant role -> Permission map. It
// must match the `tools:`/`permissionMode:` frontmatter of
// internal/install/assets/agents/*.md byte-for-byte (see
// TestPermissionTable_MatchesAgentAssets). An LLM must NEVER be allowed to
// produce these values; ProfileComposer always writes them from this table.
var PermissionTable = map[Role]Permission{
	RoleArchitect: {
		Tools:          readOnlyTools,
		PermissionMode: "",
	},
	RoleQATester: {
		Tools:          readOnlyTools,
		PermissionMode: "",
	},
	RoleDiagnostician: {
		Tools:          diagnosticianTools,
		PermissionMode: "",
	},
	RoleBackend: {
		Tools:          implementerTools,
		PermissionMode: bypassPermissions,
	},
	RoleFrontend: {
		Tools:          implementerTools,
		PermissionMode: bypassPermissions,
	},
	RoleBugHunter: {
		Tools:          implementerTools,
		PermissionMode: bypassPermissions,
	},
}

// implementerCapabilityTools is the set of tools.Tools entries that grant
// edit capability — the actual toolset IsImplementer inspects (SPEC-087 D1).
// Bash is deliberately absent: the diagnostician carries Bash to read logs
// without ever mutating code, and (since SPEC-087 D2b) qa-tester carries Bash
// to run its own gates for the same read/execute-only reason. Neither should
// become an "implementer" merely for having Bash.
var implementerCapabilityTools = map[string]bool{
	"Edit":         true,
	"Write":        true,
	"MultiEdit":    true,
	"NotebookEdit": true,
}

// IsImplementer reports whether role's permission envelope grants edit
// capability: its Tools allowlist contains at least one of
// Edit/Write/MultiEdit/NotebookEdit. Bash does NOT count.
//
// SPEC-087 D1: this used to read perm.PermissionMode == bypassPermissions as
// a proxy for edit capability, which happened to be correct only because the
// three original implementer roles were also the three roles with
// bypassPermissions. SPEC-087 D2b breaks that coincidence by giving
// qa-tester bypassPermissions too (so its own go test/lint gates run
// unattended) without granting it any edit tool — the old proxy would have
// misclassified qa-tester as an implementer the moment D2b landed. Reading
// the actual toolset is correct regardless of which roles carry
// bypassPermissions in the future.
func IsImplementer(role Role) bool {
	perm, ok := PermissionTable[role]
	if !ok {
		return false
	}
	for _, tool := range perm.Tools {
		if implementerCapabilityTools[tool] {
			return true
		}
	}
	return false
}
