package subagents

import "strings"

// Role identifies one of mneme's bundled subagent roles. Role values are
// Go-authored constants, never generated by an LLM — they are the anchor
// PermissionTable keys on.
type Role string

// The six roles mneme ships today (internal/install/assets/agents/*.md).
// StackFingerprinter/grill-driven role selection (SS-3+) may introduce new
// roles in the future, but the permission envelope for these six is fixed
// here and must never be widened by generated content.
const (
	RoleArchitect     Role = "architect"
	RoleBackend       Role = "backend"
	RoleFrontend      Role = "frontend"
	RoleQATester      Role = "qa-tester"
	RoleBugHunter     Role = "bug-hunter"
	RoleDiagnostician Role = "diagnostician"
)

// Permission describes the exact `tools:` allowlist and (optional)
// `permissionMode:` value a role's frontmatter must carry. This is the
// capability layer described in SPEC-034/SPEC-052 D3: an LLM never generates
// these values, so a subagent can never grant itself more capability than
// its role allows.
type Permission struct {
	// Tools lists the frontmatter tools allowlist in the exact order it must
	// appear on the `tools:` line.
	Tools []string

	// PermissionMode is the frontmatter `permissionMode:` value, or "" when
	// the role must NOT carry that key at all (read-only roles never bypass
	// Claude Code's permission prompts).
	PermissionMode string
}

// ToolsString renders Tools as the comma-and-space-joined string used
// verbatim on an agent's frontmatter `tools:` line, e.g.
// "Read, Grep, Glob, NotebookRead, BashOutput, mcp__mneme__*".
func (p Permission) ToolsString() string {
	return strings.Join(p.Tools, ", ")
}

// readOnlyTools is the allowlist shared by roles that only ever read code:
// no Edit/Write/MultiEdit/NotebookEdit, no Bash. SPEC-087 D2 adds
// WebSearch/WebFetch (canonical order: web-navigation tools immediately
// before mcp__mneme__*) so architect can research external references
// without gaining any mutation capability.
var readOnlyTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "BashOutput",
	"WebSearch", "WebFetch", "mcp__mneme__*",
}

// visualTools are the three browser-server MCP tool patterns mneme
// recognises today (SPEC-132 D2) — no server name in this space is stable
// (R4), so all three forms an agent might find installed are granted at
// once rather than picking one or adding per-project configuration:
//
//   - mcp__chrome-live__*                                 (chrome-live)
//   - mcp__plugin_chrome-devtools-mcp_chrome-devtools__*   (chrome-devtools MCP, as a plugin)
//   - mcp__plugin_playwright_playwright__*                 (Playwright MCP, as a plugin)
//
// UNIQUE declaration of the set (SPEC-132 Dp1): every guardian that cares
// which role has a browser reads this variable, so adding a fourth pattern
// forces touching the role lists too or the guardians go red. Ordered ASCII
// ascending (SPEC-132 Dp2) — this is the order WITHIN the block; the block
// itself always sits immediately before mcp__mneme__*, which stays the
// final entry in any list that carries it (SPEC-087 D2 precedent). The full
// list is deliberately NOT globally sorted: "mcp__mneme__*" is
// alphabetically before "mcp__plugin...", so sorting everything would move
// it out of last place and break that older rule.
var visualTools = []string{
	"mcp__chrome-live__*",
	"mcp__plugin_chrome-devtools-mcp_chrome-devtools__*",
	"mcp__plugin_playwright_playwright__*",
}

// qaTesterTools is qa-tester's own allowlist (SPEC-087 D2): readOnlyTools
// plus Bash — mirroring diagnosticianTools' shape (Bash after BashOutput) —
// so qa-tester can run its own gates (go test, lint, build) instead of
// depending on the orchestrator to run them and paste back the output. No
// Edit/Write/MultiEdit/NotebookEdit: qa-tester's entregables go through the
// spec_doc_write MCP tool (SPEC-087 D3), never a file-edit tool.
//
// SPEC-132 D1/D3: gains visualTools (immediately before mcp__mneme__*, per
// Dp2) so qa-tester can open a screen and actually look at it instead of
// declaring visual certification "pending the orchestrator" — the defect
// this spec exists to close. qa-tester stops being read-only over DATA
// (a browser can submit forms, delete records) while staying read-only over
// CODE: no edit tool is added here.
var qaTesterTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "BashOutput", "Bash",
	"WebSearch", "WebFetch",
	"mcp__chrome-live__*", "mcp__plugin_chrome-devtools-mcp_chrome-devtools__*", "mcp__plugin_playwright_playwright__*",
	"mcp__mneme__*",
}

// implementerBaseTools is the allowlist shared by the implementer roles that
// do NOT get a browser: backend and bug-hunter. Full edit toolset plus Bash.
// SPEC-087 D2 adds WebSearch/WebFetch (same canonical placement as
// readOnlyTools/qaTesterTools) immediately before mcp__mneme__*.
//
// Renamed from implementerTools (SPEC-132 D1/Dp1): before this spec every
// implementer shared one allowlist, so "implementerTools" meant "every
// implementer's tools". Since frontend gets a browser and backend/bug-hunter
// do not, that name would silently start meaning "every implementer except
// frontend" without saying so — the exact kind of quiet drift D1 exists to
// prevent. The rename forces a compile error at every use site, which is
// the cheap way to make sure each one gets reviewed.
var implementerBaseTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "NotebookEdit", "BashOutput",
	"Edit", "Write", "MultiEdit", "Bash", "WebSearch", "WebFetch", "mcp__mneme__*",
}

// frontendTools is frontend's own allowlist, split out of the former
// implementerTools so backend/bug-hunter and frontend can diverge (SPEC-132
// D1): the full edit toolset of implementerBaseTools, plus visualTools
// (immediately before mcp__mneme__*, per Dp2) so frontend can open the
// screen it just built instead of trusting that "compiles" means "renders
// correctly" — the same defect class this spec closes for qa-tester.
//
// Deliberately a LITERAL list, not a runtime composition such as
// append(implementerBaseTools, ...) (SPEC-132 Dp1 alternative 2, rejected):
// append on a slice with spare capacity can write into the backing array a
// sibling slice still references, and the whole point of this table is that
// it can be read literally, byte for byte, against the real frontmatter — a
// composed value can't offer that same guarantee at a glance.
//
// TestFrontendTools_DivergeOnlyByVisual (SPEC-132 AC4) pins that
// frontendTools never differs from implementerBaseTools by anything other
// than the browser block, so a capability added to one and not the other
// goes red instead of drifting silently.
var frontendTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "NotebookEdit", "BashOutput",
	"Edit", "Write", "MultiEdit", "Bash", "WebSearch", "WebFetch",
	"mcp__chrome-live__*", "mcp__plugin_chrome-devtools-mcp_chrome-devtools__*", "mcp__plugin_playwright_playwright__*",
	"mcp__mneme__*",
}

// diagnosticianTools is readOnlyTools's pre-SPEC-087 shape plus Bash (for
// reading logs/infra) but without any edit tool — the diagnostician reads
// and triages, never mutates. SPEC-087 D2/decision-3 deliberately leaves
// this envelope unchanged: the diagnostician does not gain web navigation
// (see TestDiagnosticianToolsExcludeWebNavigation).
var diagnosticianTools = []string{
	"Read", "Grep", "Glob", "NotebookRead", "BashOutput", "Bash", "mcp__mneme__*",
}

// bypassPermissions is the frontmatter permissionMode value implementer
// roles carry so autonomous runs are not interrupted by per-tool prompts.
// The real capability barrier is the tools: allowlist above, not this mode.
const bypassPermissions = "bypassPermissions"

// PermissionTable is the Go-authored, constant role -> Permission map. It
// must match the `tools:`/`permissionMode:` frontmatter of
// internal/install/assets/agents/*.md byte-for-byte (see
// TestPermissionTable_MatchesAgentAssets). An LLM must NEVER be allowed to
// produce these values; ProfileComposer always writes them from this table.
var PermissionTable = map[Role]Permission{
	RoleArchitect: {
		Tools:          readOnlyTools,
		PermissionMode: "",
	},
	RoleQATester: {
		Tools: qaTesterTools,
		// SPEC-087 D2b: bypassPermissions so qa-tester's own gates
		// (go test/lint/build via Bash) run unattended — without it, every
		// Bash call opens a human permission prompt and the role still can't
		// finish a review desatendido, which is the exact problem this spec
		// fixes. qa-tester is still not an implementer: the capability
		// barrier is the tools: allowlist above (no Edit/Write/MultiEdit/
		// NotebookEdit), not this mode — see IsImplementer's doc comment.
		PermissionMode: bypassPermissions,
	},
	RoleDiagnostician: {
		Tools:          diagnosticianTools,
		PermissionMode: "",
	},
	RoleBackend: {
		Tools:          implementerBaseTools,
		PermissionMode: bypassPermissions,
	},
	RoleFrontend: {
		Tools:          frontendTools,
		PermissionMode: bypassPermissions,
	},
	RoleBugHunter: {
		Tools:          implementerBaseTools,
		PermissionMode: bypassPermissions,
	},
}

// implementerCapabilityTools is the set of tools.Tools entries that grant
// edit capability — the actual toolset IsImplementer inspects (SPEC-087 D1).
// Bash is deliberately absent: the diagnostician carries Bash to read logs
// without ever mutating code, and (since SPEC-087 D2b) qa-tester carries Bash
// to run its own gates for the same read/execute-only reason. Neither should
// become an "implementer" merely for having Bash.
var implementerCapabilityTools = map[string]bool{
	"Edit":         true,
	"Write":        true,
	"MultiEdit":    true,
	"NotebookEdit": true,
}

// IsImplementer reports whether role's permission envelope grants edit
// capability: its Tools allowlist contains at least one of
// Edit/Write/MultiEdit/NotebookEdit. Bash does NOT count.
//
// SPEC-087 D1: this used to read perm.PermissionMode == bypassPermissions as
// a proxy for edit capability, which happened to be correct only because the
// three original implementer roles were also the three roles with
// bypassPermissions. SPEC-087 D2b breaks that coincidence by giving
// qa-tester bypassPermissions too (so its own go test/lint gates run
// unattended) without granting it any edit tool — the old proxy would have
// misclassified qa-tester as an implementer the moment D2b landed. Reading
// the actual toolset is correct regardless of which roles carry
// bypassPermissions in the future.
func IsImplementer(role Role) bool {
	perm, ok := PermissionTable[role]
	if !ok {
		return false
	}
	for _, tool := range perm.Tools {
		if implementerCapabilityTools[tool] {
			return true
		}
	}
	return false
}
