// Package quality — this file implements RenderReport (SPEC-117
// EPIC-calidad S3 D12): the pure renderer that turns a certificate's
// already-persisted rows into the QA report a human reads. It NEVER reads
// criteria.toml — the report is generated from the certificate's own rows,
// which is what closes D1's window: editing the file after certification
// cannot change what the report says.
package quality

import (
	"fmt"
	"sort"
	"strings"
)

// ReportGenerationMarker is the literal string RenderReport writes into
// every report it produces, and the ONE thing internal/service's Report
// checks for before overwriting an existing qa-report.md without --force
// (D12) — a report missing this marker was not generated by mneme, and
// SpecDocWrite's whole-file overwrite semantics (BL-130) make silently
// destroying a manually-authored report the worst possible first effect
// of this mechanism.
const ReportGenerationMarker = "<!-- generated by mneme quality report -->"

// ReportCheck is RenderReport's own flat projection of one certificate
// row — the leaf never imports model.QualityCheck (this package has zero
// external deps); the service layer translates, the same posture it
// already has for CheckResult/Baseline.
type ReportCheck struct {
	Seq  int
	Kind string
	Name string

	// Mode and Text are populated ONLY for criterion*-kind rows, read back
	// from the row's own Detail JSON by the caller — the criterion's
	// declared mode ("assert"/"command"/"manual") and its normative Text,
	// verbatim (D1 property 1: the certificate carries the declaration,
	// not just a verdict).
	Mode string
	Text string

	Status  string
	Summary string

	// Effect is SPEC-137 D7's own "modo" — the row's persisted
	// blocks/signable/measures/absent/stopped value, rendered as its own
	// column in the non-criterion table so a reader sees, IN THE SAME
	// LINE that gives a number, whether that number still blocks the
	// verdict or only measures it now (D11's own mitigation: a
	// constitution key changing behaviour without the file changing must
	// be visible in the result, not just in documentation).
	Effect string

	// AckedBy/AckedAt/Justification are non-empty only for a signed
	// (status=="acked") row — AC28's "quien firmo, cuando y con que
	// evidencia".
	AckedBy       string
	AckedAt       string
	Justification string
}

// ReportInput is everything RenderReport needs — a flat, already-resolved
// snapshot the service layer builds from model.* types. Every string field
// arrives pre-formatted (dates, in particular): RenderReport itself never
// touches a clock or a timezone, which is what keeps it deterministic.
type ReportInput struct {
	SpecID           string
	CertificateID    string
	HeadSHA          string
	BaseSHA          string
	Verdict          string
	ConstitutionHash string

	// CriteriaHash is the criteria/declared row's own recorded hash — empty
	// when that row never ran (the mechanism was off, or the cascade
	// stopped before it).
	CriteriaHash string

	MnemeVersion   string
	GeneratedAtUTC string

	// Evidence is the certificate's own persisted D6 sentence (SPEC-137),
	// read verbatim from the column — RenderReport never re-derives it.
	// Empty for a certificate emitted before this field existed.
	Evidence string

	Checks []ReportCheck
}

// EvidenceMissingText is what all three D6 rendering channels
// (RenderReport, `quality verify`, `quality status`) show in place of a
// certificate's own Evidence when that field is empty — a certificate
// emitted before SPEC-137 existed. Never a fabricated sentence.
const EvidenceMissingText = "certificado emitido antes de esta version: sin linea de evidencia"

// RenderReport renders in into the exact QA report document mneme writes
// via SpecDocWrite kind qa-report (D12). Deterministic (AC28): the SAME
// input produces the SAME bytes, every time — checks are sorted by Seq
// (never iterated from a map), and the only timestamp printed anywhere in
// the body is the caller-supplied GeneratedAtUTC (the certificate's own
// creation time), never "now".
func RenderReport(in ReportInput) string {
	var b strings.Builder

	fmt.Fprintf(&b, "%s\n", ReportGenerationMarker)
	fmt.Fprintf(&b, "# Informe de calidad — %s\n\n", in.SpecID)
	fmt.Fprintf(&b, "- Certificado: %s\n", in.CertificateID)
	fmt.Fprintf(&b, "- head_sha: %s\n", in.HeadSHA)
	if in.BaseSHA != "" {
		fmt.Fprintf(&b, "- base_sha: %s\n", in.BaseSHA)
	}
	fmt.Fprintf(&b, "- Veredicto: %s\n", in.Verdict)
	fmt.Fprintf(&b, "- Hash de constitucion: %s\n", in.ConstitutionHash)
	if in.CriteriaHash != "" {
		fmt.Fprintf(&b, "- Hash de criterios: %s\n", in.CriteriaHash)
	}
	fmt.Fprintf(&b, "- Generado: %s\n\n", in.GeneratedAtUTC)

	// SPEC-137 D6: the evidence sentence is the first line of the body,
	// before any table — read verbatim from the certificate's own
	// persisted column, never re-derived here.
	evidence := in.Evidence
	if evidence == "" {
		evidence = EvidenceMissingText
	}
	fmt.Fprintf(&b, "%s\n\n", evidence)

	criterionChecks := make([]ReportCheck, 0, len(in.Checks))
	otherChecks := make([]ReportCheck, 0, len(in.Checks))
	for _, c := range in.Checks {
		if strings.HasPrefix(c.Kind, "criterion") {
			criterionChecks = append(criterionChecks, c)
		} else {
			otherChecks = append(otherChecks, c)
		}
	}
	sort.Slice(criterionChecks, func(i, j int) bool { return criterionChecks[i].Seq < criterionChecks[j].Seq })
	sort.Slice(otherChecks, func(i, j int) bool { return otherChecks[i].Seq < otherChecks[j].Seq })

	fmt.Fprintf(&b, "## Criterios\n\n")
	if len(criterionChecks) == 0 {
		fmt.Fprintf(&b, "Este certificado no tiene ninguna fila de criterio.\n\n")
	} else {
		fmt.Fprintf(&b, "| id | modo | estado | texto | resumen |\n|---|---|---|---|---|\n")
		for _, c := range criterionChecks {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", c.Name, c.Mode, c.Status, escapeTableCell(c.Text), escapeTableCell(c.Summary))
		}
		fmt.Fprintf(&b, "\n")

		signedAny := false
		for _, c := range criterionChecks {
			if c.Status != "acked" {
				continue
			}
			if !signedAny {
				fmt.Fprintf(&b, "### Firmas\n\n")
				signedAny = true
			}
			fmt.Fprintf(&b, "- %s: firmado por %s el %s — %s\n", c.Name, c.AckedBy, c.AckedAt, c.Justification)
		}
		if signedAny {
			fmt.Fprintf(&b, "\n")
		}
	}

	if len(otherChecks) > 0 {
		fmt.Fprintf(&b, "## Gates, cobertura y cliquet\n\n")
		fmt.Fprintf(&b, "| kind | name | estado | modo |\n|---|---|---|---|\n")
		for _, c := range otherChecks {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", c.Kind, c.Name, c.Status, c.Effect)
		}
		fmt.Fprintf(&b, "\n")
	}

	fmt.Fprintf(&b, "---\nGenerado por %s (`mneme quality report %s`).\n", mnemeVersionOrUnknown(in.MnemeVersion), in.SpecID)

	return b.String()
}

// mnemeVersionOrUnknown avoids an empty, confusing "Generado por  (...)"
// line when the caller never set MnemeVersion.
func mnemeVersionOrUnknown(v string) string {
	if v == "" {
		return "mneme"
	}
	return "mneme " + v
}

// escapeTableCell replaces a literal pipe with its HTML entity so a
// criterion's own text (which may legitimately contain "|", e.g. inside a
// code sample) never breaks the surrounding Markdown table's column count.
func escapeTableCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
